### ISSUE TITLE
Allow multi-database support

### ISSUE THREAD

**Issue by lynncyrin** [SexualHealthInnovations/django-wizard-builder#24]
When running django wizard builder on a multi-db setup, [this line](https://github.com/SexualHealthInnovations/django-wizard-builder/blob/b9842c9eab7fa568827fd5addd4e63f84a1f8138/wizard_builder/migrations/0001_initial.py#L188) in the first migration tries to evaluate...

```
wizard_builder.models.get_page
```

...even when the migration is not going to be applied to the currently selected database. This results in this error

```
django.db.utils.OperationalError: no such table: wizard_builder_questionpage
```

because, accurately, that table does not exist on the currently selected database.

The response I would expect from django itself is not evaluating `wizard_builder.models.get_page` at all, but given that, that isn't the case, a working fix I have locally is ignoring the `OperationalError` exception in `get_page`. So:

```diff
def get_page():
    try:
        return QuestionPage.objects.latest('position').pk
-    except ObjectDoesNotExist:
+    except (ObjectDoesNotExist, OperationalError):
        return None
```

I'll have a PR as soon as I can figure out how to add test coverage for this.

(see also: https://github.com/SexualHealthInnovations/callisto-core/issues/135)

**Comment by lynnco** [comment]
The different between this issue and SexualHealthInnovations/callisto-core#135 / https://github.com/SexualHealthInnovations/callisto-core/pull/136, is that this issue requires a migration to be run against the alternate database, instead of just adding the alternate database to the settings.

It may be a good idea to test callisto-core with a migration against the alternate database also

**Comment by lynnco** [comment]
So it appears the cause of this particular issue is a misconfigured [router](https://docs.djangoproject.com/en/1.10/topics/db/multi-db/#automatic-database-routing). I think that django-wizard-builder **should** be raising `OperationalError` in this case. There are likely still some tests for routing / multidb that can be added to django-wizard-builder, but I can't say for sure what they are at this point.

**Comment by kelseyq** [comment]
do we need `get_page`? i remember it being a pain in the ass in previous migrations too

**Comment by lynnco** [comment]
It's used [in two places](https://github.com/SexualHealthInnovations/django-wizard-builder/search?utf8=%E2%9C%93&q=get_page), but I can't say how integral it is. I should probably evaluate it as a part of the upcoming record form milestone

**Comment by lynnco** [comment]
(most of) this issue was handled by the `get_page` change in https://github.com/SexualHealthInnovations/django-wizard-builder/issues/24

I want to leave it open just in case, though

**Comment by lynncyrin** [comment]
done
