### ISSUE TITLE
Selecting PageBase object in admin produces an error

### ISSUE THREAD

**Issue by lynnco** [SexualHealthInnovations/django-wizard-builder#29]

**Comment by lynnco** [comment]
this one 
![image](https://cloud.githubusercontent.com/assets/5768468/24562194/d21a3d4c-15fe-11e7-8970-051a656037bd.png)

**Comment by kelseyq** [comment]
why is this visible in admin?

**Comment by lynnco** [comment]
No idea. It might be because my local db setup is... a bit hacked together

**Comment by lynnco** [comment]
this was definitely because of my hacky local setup, closing!
