### ISSUE TITLE
Remove ContentTypes dependency

### ISSUE THREAD

**Issue by lynnco** [SexualHealthInnovations/django-wizard-builder#39]
WIP, will dump my notes here

**Comment by lynnco** [comment]
the contenttypes dependency is causing problems with multi-tenant callisto, so the plan is to remove django-polymorphic and implement that functionality by some other means

**Comment by lynnco** [comment]
here's my implementation ideas from another thread

---

My implementation for this would be using a proxy models for the (`PageBase` and `FormQuestion`) subclasses, and moving all the data to the (`PageBase` and `FormQuestion`) classes. The proxy models would be "weird" in that, for example, the `SingleLineText` proxy model would have empty fields for `RadioButton` on it. But I think that quirk is worth it, because none of the currently existing `ForeignKey`s to (`PageBase` and `FormQuestion`) would need to be changed.

I can then change the current `polymorphic_ctype_id` field to something like `formquestion_proxy_type` with a `CharField` that defines the path to the proxy model. This would essentially be a quick and dirty re-implementation of `django-polymorphic`, but I think that's worth the work. I could also abstract the alternate polymorphic functionality into a standalone django package

**Comment by lynnco** [comment]
https://github.com/craigds/django-typed-models looks like it actually does everything that I wanted! 🎉  for researching!!!

**Comment by lynnco** [comment]
similar packages https://djangopackages.org/grids/g/model-inheritance/

**Comment by lynnco** [comment]
current options

- https://github.com/jazzband/django-model-utils
- https://github.com/craigds/django-typed-models

**Comment by lynnco** [comment]
Alright, I'm definitely going to use one of the two options above instead of creating my own solution. Just need to decide which one

**Comment by kelseyq** [comment]
neither of them depend on ContentType?

**Comment by lynnco** [comment]
Yep. I'm still reading about how the first one works, but the second one works via `type='wizard_builder.CheckBox'` field on the base class

**Comment by lynnco** [comment]
the `InheritanceManager` option has an implementation in its example blog

```python
    def select_subclasses(self, *subclasses):
        if not subclasses:
            subclasses = [o for o in dir(self.model)
                          if isinstance(getattr(self.model, o), SingleRelatedObjectDescriptor)\
                          and issubclass(getattr(self.model,o).related.model, self.model)]
        new_qs = self.select_related(*subclasses)
        new_qs.subclasses = subclasses
        return new_qs
```

that looks a lot like a thing I implemented yesterday

```python
def _translate_obj_to_most_specific_subclass(obj):
    '''
        given an obj, translate that object to its most specific subclass
        the subclass will have all the attributes of its parent classes,
        and populate them all on creation

        ex: for CheckBox (which is FormQuestion > MultipleChoice > Checkbox)
        - if you get a MultipleChoice that's also a CheckBox, return Checkbox
        - CheckBox will populate all the attributes MultipleChoice defines
        - CheckBox will also populate FormQuestion attributes

        this function needs to be recursive, so that it can resolve (ex)
        FormQuestion to Checkbox (two steps down)
    '''
    database = obj._state.db
    for subclass in obj.__class__.__subclasses__():
        for field in subclass._meta.fields:
            query = {field.name: obj}
            if isinstance(field, OneToOneField) \
                    and field.remote_field.parent_link \
                    and subclass.objects.using(database).filter(**query):
                obj = subclass.objects.using(database).get(**query)
                return _translate_obj_to_most_specific_subclass(obj)
    return obj
```

**Comment by lynnco** [comment]
Alright, I've got a handle on how the two options work.

https://django-model-utils.readthedocs.io/en/latest/managers.html#inheritancemanager works via adding a manager to your objects does a recursive look through all the related fields, and re-assigns queryset results to the most specific subclass for each result.

Its basically the `_translate_obj_to_most_specific_subclass` I linked above, but as a manager.

---

https://github.com/craigds/django-typed-models is django polymorphic, except with a `type` `CharField` instead of a `contenttype` `ForeignKey`

**Comment by lynnco** [comment]
I'm thinking that `InheritanceManager` is the better option for wizard builder than `django-typed-models`. My thoughts

- InheritanceManager is supported by https://github.com/jazzband, https://github.com/craigds/django-typed-models has a single "owner". Callisto already uses a few other things supported by jazzband, even.
- InheritanceManager does not require any custom model fields (!!!)
- As far as performance is concerned (I believe) django-polymorphic > django-typed-models > InheritanceManager, but wizard_builder as Callisto implements it does not need to be high performance
- InheritanceManager has the ability to "gotcha! wrong model" you, because the type down-casting kicks in when you call `BaseModel.objects`, as opposed to when you access that model by other means (ex: with `relatedmodel.basemodel`). django-polymorphic and django-typed-models don't have this problem

**Comment by lynnco** [comment]
I think `InheritanceManager` stands out by not requiring any custom model fields, and because of that easily overcomes its deficits.

I'ma take a break for a bit, and make the final decision and start writing up a plan after said break

**Comment by lynnco** [comment]
Alright, so I'm definitely gonna go for `InheritanceManager`, and on top of that I'm going to try to make this change mostly backwards compatible, for example - 

if `relatedmodel.basemodel` works the way I think it does, and doesn't auto down-cast, I'm going to change the attribute to `relatedmodel.basemodel_fk` and create a `relatedmodel.basemodel` attribute that does the down-casting

**Comment by kelseyq** [comment]
Sounds good. I would say that backwards compatibility is not the biggest priority here (the priority is mainly just the form continuing to work) so I wouldn't bend over backwards to get it

**Comment by lynnco** [comment]
The backwards compatibility thing is mostly so that I can keep the changes as isolated to the models as possible. Like, I'd this change not to result in a ton of changes to https://github.com/SexualHealthInnovations/callisto-core

**Comment by lynnco** [comment]
Alright so here's the plan

- [ ] remove django-polymorphic from PageBase
- [ ] remove django-polymorphic from FormQuestion
- [ ] add InheritanceManager to PageBase
- [ ] add InheritanceManager to FormQuestion
- [ ] update fk to FormQuestion on PageBase
- [ ] update fk to QuestionPage (not PageBase!) on FormQuestion
- [ ] update fk to FormQuestion on callisto-core.evaluation.EvaluationField (in https://github.com/SexualHealthInnovations/callisto-core)
- [ ] update fk to MultipleChoice (not FormQuestion!) on Choice
- [ ] update fk to PageBase on Conditional
- [ ] update fk to FormQuestion on Conditional
- [ ] (ideally) do all of this without changing the current tests
