### ISSUE TITLE
Update setup.py

### ISSUE THREAD

**Issue by lynncyrin** [SexualHealthInnovations/django-wizard-builder#43]
ref https://stackoverflow.com/questions/14399534/reference-requirements-txt-for-the-install-requires-kwarg-in-setuptools-setup-py#comment63662558_16624700

**Comment by lynnco** [comment]
I added this

```
    install_requires=[
        'django-formtools>=2.0',
        'django-model-utils>=3.0',
    ],
```

to setup.py and removed this lines from requirements.txt, and it worked, but like,

the install took 100x as long as it normally does, and was hanging most of that time
