### ISSUE TITLE
fix flakey admin tests

### ISSUE THREAD

**Issue by lynncyrin** [SexualHealthInnovations/django-wizard-builder#45]
[the admin tests](https://github.com/SexualHealthInnovations/django-wizard-builder/blob/faa9a6def078ea928c12e7f67ff6eef486737713/tests/test_admin.py) are currently implemented as flaky selenium tests, when they would be much better implemented as tests against ModelAdmin

**Comment by lynnco** [comment]
and they are -very- flakey too. they timeout on something like 20% of all the builds

**Comment by lynnco** [comment]
the issue that's making the tests flakey is described here https://docs.djangoproject.com/en/1.11/topics/testing/tools/#liveservertestcase

specifically
> When using an in-memory SQLite database to run the tests, the same database connection will be shared by two threads in parallel: the thread in which the live server is run and the thread in which the test case is run. It’s important to prevent simultaneous database queries via this shared connection by the two threads, as that may sometimes randomly cause the tests to fail.

My original plan was to rewrite the tests to test ModelAdmin, but changing those tests to use the postgres database is a much faster option

**Comment by lynnco** [comment]
(blegh I'm so back and forth)

changing these tests to use a postgres db would require adding a 3rd database or making all the test databases postgres

so I'm looking at the modeladmin tests again https://github.com/django/django/blob/master/tests/modeladmin/tests.py

**Comment by lynnco** [comment]
Issue is still present https://travis-ci.org/SexualHealthInnovations/django-wizard-builder/jobs/239814657
