### ISSUE TITLE
clicking on a model from its parent's admin doesn't open an admin for the subclass

### ISSUE THREAD

**Issue by lynncyrin** [SexualHealthInnovations/django-wizard-builder#56]

**Comment by lynnco** [comment]
eg if I'm in the FormQuestion admin and click a Checkbox, the admin that gets opened is the Checkbox admin

**Comment by lynnco** [comment]
this issue is very confusing, but not totally broken. you can still go into the Checkbox admin and edit the checkbox there

**Comment by lynncyrin** [comment]
not relevant as of https://github.com/SexualHealthInnovations/django-wizard-builder/issues/144
